name: Pull request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: Récuperation du repo
        uses: actions/checkout@v2
      - name: Récuperation de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn test
  build-app:
    needs: test-unitaire
    runs-on: ubuntu-latest
    steps:
      - name: Récuperation du repo
        uses: actions/checkout@v2
      - name: Récuperation de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Création du jar
        run: mvn package
      - name: Upload du jar
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: ./target/testDemo-0.0.1-SNAPSHOT.jar